### ISSUE TITLE
Unfortunately MAS Sample has stopped on Android (ANR)

### ISSUE THREAD

**Issue by pradeepgudipati** [CAAPIM/Releases#1]
In the console the Compilation throws the below error, we are using the below libraries  (Which are also present in the MAS Sample. 

mobile-api-gateway-sdk-3.2.00.211.aar
mobile-app-service-sdk-1.2.00-CR1.211.aar
mobile-app-service-sdk-ui-1.2.00-CR1.211.aar

Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketNetworkModule$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence$2) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.

**Comment by witrisna** [comment]
This is a known issue: https://github.com/eclipse/paho.mqtt.android/issues/79.
Those warning messages should not impact any feature of MASMessaging,  we will monitor the release schedule and upgrade the paho library in the future.

**Comment by ForceKinetics** [comment]
We're still keeping an eye on this; as described in the paho issue, we're waiting for the 1.3.0 release of the library.

**Comment by ForceKinetics** [comment]
We continue to monitor this going into our newest release, but paho is on the same released version as my last comment.

**Comment by witrisna** [comment]
Paho Client has been upgraded, the issue should be resolved in MAG SDK 1.6.
